name: CMake MSVC

on: push

jobs:
  yasm:
    runs-on: windows-latest
    steps:
      - name: Restore yasm
        id: restore-yasm
        uses: actions/cache/restore@v3
        with:
          path: |
            ${{ github.workspace }}/yasm
          key: yasm
      - name: Download yasm sources
        if: ${{ !steps.restore-yasm.outputs.cache-hit }}
        uses: actions/checkout@v3
        with:
          repository: yasm/yasm
          path: yasm-src
      - name: Build and install yasm
        if: ${{ !steps.restore-yasm.outputs.cache-hit }}
        run: |
          cmake -S yasm-src -B yasm-build -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/yasm -DCMAKE_INSTALL_LIBDIR=bin -DCMAKE_INSTALL_BINDIR=bin -A x64 -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded
          cmake --build yasm-build --parallel --config Release
          cmake --install yasm-build --config Release
      - name: Cache yasm
        if: ${{ !steps.restore-yasm.outputs.cache-hit }}
        uses: actions/cache/save@v3
        with:
          path: |
            ${{ github.workspace }}/yasm
          key: yasm
  build:
    defaults:
      run:
        shell: cmd
    needs:
      yasm
    strategy:
      fail-fast: false
      matrix:
        # currently windows-latest==windows-2022
        # windows-2022: VS2022
        # windows-2019: VS2019
        os: [windows-2022, windows-2019]
        arch: [x86, x64, amd64_arm, amd64_arm64]
        shared: [ON, OFF]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Restore yasm
        uses: actions/cache/restore@v3
        with:
          path: |
            ${{ github.workspace }}/yasm
          key: yasm
      - name: add yasm to PATH
        run: echo "${{ github.workspace }}/yasm/bin" >> %GITHUB_PATH%"
      - name: CMake
        run: cmake -S ports/cmake -B build -DYASM_ASSEMBLER=${{ github.workspace }}/yasm/bin/vsyasm.exe -DBUILD_SHARED_LIBS=${{ matrix.shared }}
      - name: CMake --build
        run: cmake --build build --verbose
